export const ADD_CONTACT = "ADD_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const SET_FORM_FIELD = "SET_FORM_FIELD";
export const RESET_CONTACT_FORM = "RESET_CONTACT_FORM";
export const SET_CONTACT_FORM = "SET_CONTACT_FORM";
